#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

killall -q polybar
killall -q dunst
killall -q picom
killall -q redshift
killall -q /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
pkill -9 -f battery-notify.py

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

picom &

bspc config border_width         1
bspc config window_gap           0
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config ignore_ewmh_focus true


bspc config focused_border_color "454545"
bspc config normal_border_color "1a1a1a"

bspc rule -a discord desktop='^4' follow=off focus=off
bspc rule -a 'Minecraft* 1.19.4' desktop='^2'
# bspc rule -a Brave-browser monitor='
bspc rule -a 'brave' rectangle=593x427+0+0 center=true

xsetroot -cursor_name left_ptr &
xinput set-prop 12 309 1 &
polybar &
dunst &
hsetroot -solid '#000000'
redshift -l 13.065220:77.605790 &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

/home/gaurav/linux-utils/battery-notify.py
